C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
C:\Users\wgacol\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\wgacol\\Documents\\Proyecto\\COL\\validacion FE\\dist\\validacionFE.py': [Errno 2] No such file or directory
